on: [push]


pull_request:
  branches:
    - main
    - develop
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: keikishim2/my-javascript-action@v1
      with:
        who-to-greet: 'Keikishim'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"